{% set name = "itrm" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: 128c8adc0e6b690b1ee480f2b2ef97bf39d51ae5431c4f67a3f662e27abaf5c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
