{% set name = "itrm" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: 7a57d5911597af828f38a5d301e19752b206220645d2a0cc23cc13cac4059fe6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
