{% set name = "itrm" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: 62c0652108f12155bdcab1087b3d456b3891d8462666da915da08b3f2ea65098

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
