{% set name = "itrm" %}
{% set version = "1.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: 77ead172ec1c1b76256b2ee31b5dbb190ae4fd62f849c4faa46d13be321e4a86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
