{% set python_min = python_min|default("0.1a0") %}
{% set name = "itrm" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: f5d7588886b09b76a4f31aec76bf75c175f906551163ee5ed374d1d99697a97a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=45
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
