{% set name = "itrm" %}
{% set version = "1.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/itrm-{{ version }}.tar.gz
  sha256: a99aef88d36363344a9000e7ff55764e74516f31725961c5017f4e6710b29d81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - pip
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - itrm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/davidwoodburn/itrm
  summary: Interactive Terminal Utilities
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
